#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleBDD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PandamiV1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertAdresses(Adresses instance);
    partial void UpdateAdresses(Adresses instance);
    partial void DeleteAdresses(Adresses instance);
    partial void InsertFeats(Feats instance);
    partial void UpdateFeats(Feats instance);
    partial void DeleteFeats(Feats instance);
    partial void InsertMembres(Membres instance);
    partial void UpdateMembres(Membres instance);
    partial void DeleteMembres(Membres instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleBDD.Properties.Settings.Default.PandamiV1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adresses> Adresses
		{
			get
			{
				return this.GetTable<Adresses>();
			}
		}
		
		public System.Data.Linq.Table<Feats> Feats
		{
			get
			{
				return this.GetTable<Feats>();
			}
		}
		
		public System.Data.Linq.Table<Membres> Membres
		{
			get
			{
				return this.GetTable<Membres>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adresses")]
	public partial class Adresses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NumeroDeVoie;
		
		private string _NomDeVoie;
		
		private string _CodePostal;
		
		private string _Ville;
		
		private float _latitude;
		
		private float _longitude;
		
		private EntitySet<Feats> _Feats;
		
		private EntitySet<Membres> _Membres;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNumeroDeVoieChanging(string value);
    partial void OnNumeroDeVoieChanged();
    partial void OnNomDeVoieChanging(string value);
    partial void OnNomDeVoieChanged();
    partial void OnCodePostalChanging(string value);
    partial void OnCodePostalChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnlatitudeChanging(float value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(float value);
    partial void OnlongitudeChanged();
    #endregion
		
		public Adresses()
		{
			this._Feats = new EntitySet<Feats>(new Action<Feats>(this.attach_Feats), new Action<Feats>(this.detach_Feats));
			this._Membres = new EntitySet<Membres>(new Action<Membres>(this.attach_Membres), new Action<Membres>(this.detach_Membres));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDeVoie", DbType="NVarChar(MAX)")]
		public string NumeroDeVoie
		{
			get
			{
				return this._NumeroDeVoie;
			}
			set
			{
				if ((this._NumeroDeVoie != value))
				{
					this.OnNumeroDeVoieChanging(value);
					this.SendPropertyChanging();
					this._NumeroDeVoie = value;
					this.SendPropertyChanged("NumeroDeVoie");
					this.OnNumeroDeVoieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomDeVoie", DbType="NVarChar(MAX)")]
		public string NomDeVoie
		{
			get
			{
				return this._NomDeVoie;
			}
			set
			{
				if ((this._NomDeVoie != value))
				{
					this.OnNomDeVoieChanging(value);
					this.SendPropertyChanging();
					this._NomDeVoie = value;
					this.SendPropertyChanged("NomDeVoie");
					this.OnNomDeVoieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostal", DbType="NVarChar(MAX)")]
		public string CodePostal
		{
			get
			{
				return this._CodePostal;
			}
			set
			{
				if ((this._CodePostal != value))
				{
					this.OnCodePostalChanging(value);
					this.SendPropertyChanging();
					this._CodePostal = value;
					this.SendPropertyChanged("CodePostal");
					this.OnCodePostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(MAX)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Real NOT NULL")]
		public float latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Real NOT NULL")]
		public float longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresses_Feats", Storage="_Feats", ThisKey="Id", OtherKey="AdresseId")]
		public EntitySet<Feats> Feats
		{
			get
			{
				return this._Feats;
			}
			set
			{
				this._Feats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresses_Membres", Storage="_Membres", ThisKey="Id", OtherKey="AdresseId")]
		public EntitySet<Membres> Membres
		{
			get
			{
				return this._Membres;
			}
			set
			{
				this._Membres.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Feats(Feats entity)
		{
			this.SendPropertyChanging();
			entity.Adresses = this;
		}
		
		private void detach_Feats(Feats entity)
		{
			this.SendPropertyChanging();
			entity.Adresses = null;
		}
		
		private void attach_Membres(Membres entity)
		{
			this.SendPropertyChanging();
			entity.Adresses = this;
		}
		
		private void detach_Membres(Membres entity)
		{
			this.SendPropertyChanging();
			entity.Adresses = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feats")]
	public partial class Feats : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _CreationDate;
		
		private System.DateTime _RealisationDate;
		
		private System.DateTime _HeureDebut;
		
		private System.DateTime _HeureFin;
		
		private System.Nullable<System.DateTime> _AcceptationDate;
		
		private System.Nullable<System.DateTime> _EnCoursRealisation;
		
		private System.Nullable<System.DateTime> _SurPlace;
		
		private System.Nullable<System.DateTime> _FinFeatHelper;
		
		private System.Nullable<System.DateTime> _ClotureDate;
		
		private System.Nullable<System.DateTime> _SommePrevoir;
		
		private System.Nullable<float> _SommeAvancee;
		
		private System.Nullable<float> _SommeRembourseeDate;
		
		private System.Nullable<System.DateTime> _AnnulationDate;
		
		private bool _EchangeMonetaire;
		
		private System.Nullable<int> _CreateurId;
		
		private System.Nullable<int> _TypeId;
		
		private System.Nullable<int> _AdresseId;
		
		private EntityRef<Adresses> _Adresses;
		
		private EntityRef<Membres> _Membres;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    partial void OnRealisationDateChanging(System.DateTime value);
    partial void OnRealisationDateChanged();
    partial void OnHeureDebutChanging(System.DateTime value);
    partial void OnHeureDebutChanged();
    partial void OnHeureFinChanging(System.DateTime value);
    partial void OnHeureFinChanged();
    partial void OnAcceptationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAcceptationDateChanged();
    partial void OnEnCoursRealisationChanging(System.Nullable<System.DateTime> value);
    partial void OnEnCoursRealisationChanged();
    partial void OnSurPlaceChanging(System.Nullable<System.DateTime> value);
    partial void OnSurPlaceChanged();
    partial void OnFinFeatHelperChanging(System.Nullable<System.DateTime> value);
    partial void OnFinFeatHelperChanged();
    partial void OnClotureDateChanging(System.Nullable<System.DateTime> value);
    partial void OnClotureDateChanged();
    partial void OnSommePrevoirChanging(System.Nullable<System.DateTime> value);
    partial void OnSommePrevoirChanged();
    partial void OnSommeAvanceeChanging(System.Nullable<float> value);
    partial void OnSommeAvanceeChanged();
    partial void OnSommeRembourseeDateChanging(System.Nullable<float> value);
    partial void OnSommeRembourseeDateChanged();
    partial void OnAnnulationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnnulationDateChanged();
    partial void OnEchangeMonetaireChanging(bool value);
    partial void OnEchangeMonetaireChanged();
    partial void OnCreateurIdChanging(System.Nullable<int> value);
    partial void OnCreateurIdChanged();
    partial void OnTypeIdChanging(System.Nullable<int> value);
    partial void OnTypeIdChanged();
    partial void OnAdresseIdChanging(System.Nullable<int> value);
    partial void OnAdresseIdChanged();
    #endregion
		
		public Feats()
		{
			this._Adresses = default(EntityRef<Adresses>);
			this._Membres = default(EntityRef<Membres>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealisationDate", DbType="DateTime2 NOT NULL")]
		public System.DateTime RealisationDate
		{
			get
			{
				return this._RealisationDate;
			}
			set
			{
				if ((this._RealisationDate != value))
				{
					this.OnRealisationDateChanging(value);
					this.SendPropertyChanging();
					this._RealisationDate = value;
					this.SendPropertyChanged("RealisationDate");
					this.OnRealisationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureDebut", DbType="DateTime2 NOT NULL")]
		public System.DateTime HeureDebut
		{
			get
			{
				return this._HeureDebut;
			}
			set
			{
				if ((this._HeureDebut != value))
				{
					this.OnHeureDebutChanging(value);
					this.SendPropertyChanging();
					this._HeureDebut = value;
					this.SendPropertyChanged("HeureDebut");
					this.OnHeureDebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureFin", DbType="DateTime2 NOT NULL")]
		public System.DateTime HeureFin
		{
			get
			{
				return this._HeureFin;
			}
			set
			{
				if ((this._HeureFin != value))
				{
					this.OnHeureFinChanging(value);
					this.SendPropertyChanging();
					this._HeureFin = value;
					this.SendPropertyChanged("HeureFin");
					this.OnHeureFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptationDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> AcceptationDate
		{
			get
			{
				return this._AcceptationDate;
			}
			set
			{
				if ((this._AcceptationDate != value))
				{
					this.OnAcceptationDateChanging(value);
					this.SendPropertyChanging();
					this._AcceptationDate = value;
					this.SendPropertyChanged("AcceptationDate");
					this.OnAcceptationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnCoursRealisation", DbType="DateTime2")]
		public System.Nullable<System.DateTime> EnCoursRealisation
		{
			get
			{
				return this._EnCoursRealisation;
			}
			set
			{
				if ((this._EnCoursRealisation != value))
				{
					this.OnEnCoursRealisationChanging(value);
					this.SendPropertyChanging();
					this._EnCoursRealisation = value;
					this.SendPropertyChanged("EnCoursRealisation");
					this.OnEnCoursRealisationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurPlace", DbType="DateTime2")]
		public System.Nullable<System.DateTime> SurPlace
		{
			get
			{
				return this._SurPlace;
			}
			set
			{
				if ((this._SurPlace != value))
				{
					this.OnSurPlaceChanging(value);
					this.SendPropertyChanging();
					this._SurPlace = value;
					this.SendPropertyChanged("SurPlace");
					this.OnSurPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinFeatHelper", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FinFeatHelper
		{
			get
			{
				return this._FinFeatHelper;
			}
			set
			{
				if ((this._FinFeatHelper != value))
				{
					this.OnFinFeatHelperChanging(value);
					this.SendPropertyChanging();
					this._FinFeatHelper = value;
					this.SendPropertyChanged("FinFeatHelper");
					this.OnFinFeatHelperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClotureDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ClotureDate
		{
			get
			{
				return this._ClotureDate;
			}
			set
			{
				if ((this._ClotureDate != value))
				{
					this.OnClotureDateChanging(value);
					this.SendPropertyChanging();
					this._ClotureDate = value;
					this.SendPropertyChanged("ClotureDate");
					this.OnClotureDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SommePrevoir", DbType="DateTime2")]
		public System.Nullable<System.DateTime> SommePrevoir
		{
			get
			{
				return this._SommePrevoir;
			}
			set
			{
				if ((this._SommePrevoir != value))
				{
					this.OnSommePrevoirChanging(value);
					this.SendPropertyChanging();
					this._SommePrevoir = value;
					this.SendPropertyChanged("SommePrevoir");
					this.OnSommePrevoirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SommeAvancee", DbType="Real")]
		public System.Nullable<float> SommeAvancee
		{
			get
			{
				return this._SommeAvancee;
			}
			set
			{
				if ((this._SommeAvancee != value))
				{
					this.OnSommeAvanceeChanging(value);
					this.SendPropertyChanging();
					this._SommeAvancee = value;
					this.SendPropertyChanged("SommeAvancee");
					this.OnSommeAvanceeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SommeRembourseeDate", DbType="Real")]
		public System.Nullable<float> SommeRembourseeDate
		{
			get
			{
				return this._SommeRembourseeDate;
			}
			set
			{
				if ((this._SommeRembourseeDate != value))
				{
					this.OnSommeRembourseeDateChanging(value);
					this.SendPropertyChanging();
					this._SommeRembourseeDate = value;
					this.SendPropertyChanged("SommeRembourseeDate");
					this.OnSommeRembourseeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnulationDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> AnnulationDate
		{
			get
			{
				return this._AnnulationDate;
			}
			set
			{
				if ((this._AnnulationDate != value))
				{
					this.OnAnnulationDateChanging(value);
					this.SendPropertyChanging();
					this._AnnulationDate = value;
					this.SendPropertyChanged("AnnulationDate");
					this.OnAnnulationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EchangeMonetaire", DbType="Bit NOT NULL")]
		public bool EchangeMonetaire
		{
			get
			{
				return this._EchangeMonetaire;
			}
			set
			{
				if ((this._EchangeMonetaire != value))
				{
					this.OnEchangeMonetaireChanging(value);
					this.SendPropertyChanging();
					this._EchangeMonetaire = value;
					this.SendPropertyChanged("EchangeMonetaire");
					this.OnEchangeMonetaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateurId", DbType="Int")]
		public System.Nullable<int> CreateurId
		{
			get
			{
				return this._CreateurId;
			}
			set
			{
				if ((this._CreateurId != value))
				{
					if (this._Membres.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreateurIdChanging(value);
					this.SendPropertyChanging();
					this._CreateurId = value;
					this.SendPropertyChanged("CreateurId");
					this.OnCreateurIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", DbType="Int")]
		public System.Nullable<int> TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresseId", DbType="Int")]
		public System.Nullable<int> AdresseId
		{
			get
			{
				return this._AdresseId;
			}
			set
			{
				if ((this._AdresseId != value))
				{
					if (this._Adresses.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdresseIdChanging(value);
					this.SendPropertyChanging();
					this._AdresseId = value;
					this.SendPropertyChanged("AdresseId");
					this.OnAdresseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresses_Feats", Storage="_Adresses", ThisKey="AdresseId", OtherKey="Id", IsForeignKey=true)]
		public Adresses Adresses
		{
			get
			{
				return this._Adresses.Entity;
			}
			set
			{
				Adresses previousValue = this._Adresses.Entity;
				if (((previousValue != value) 
							|| (this._Adresses.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adresses.Entity = null;
						previousValue.Feats.Remove(this);
					}
					this._Adresses.Entity = value;
					if ((value != null))
					{
						value.Feats.Add(this);
						this._AdresseId = value.Id;
					}
					else
					{
						this._AdresseId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Adresses");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Membres_Feats", Storage="_Membres", ThisKey="CreateurId", OtherKey="Id", IsForeignKey=true)]
		public Membres Membres
		{
			get
			{
				return this._Membres.Entity;
			}
			set
			{
				Membres previousValue = this._Membres.Entity;
				if (((previousValue != value) 
							|| (this._Membres.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Membres.Entity = null;
						previousValue.Feats.Remove(this);
					}
					this._Membres.Entity = value;
					if ((value != null))
					{
						value.Feats.Add(this);
						this._CreateurId = value.Id;
					}
					else
					{
						this._CreateurId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Membres");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Membres")]
	public partial class Membres : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Email;
		
		private string _Nom;
		
		private string _Prenom;
		
		private System.DateTime _Naissance;
		
		private string _Telephone;
		
		private System.DateTime _Inscription;
		
		private string _Mdp;
		
		private System.Nullable<int> _SexeId;
		
		private System.Nullable<int> _AdresseId;
		
		private EntitySet<Feats> _Feats;
		
		private EntityRef<Adresses> _Adresses;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnNaissanceChanging(System.DateTime value);
    partial void OnNaissanceChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnInscriptionChanging(System.DateTime value);
    partial void OnInscriptionChanged();
    partial void OnMdpChanging(string value);
    partial void OnMdpChanged();
    partial void OnSexeIdChanging(System.Nullable<int> value);
    partial void OnSexeIdChanged();
    partial void OnAdresseIdChanging(System.Nullable<int> value);
    partial void OnAdresseIdChanged();
    #endregion
		
		public Membres()
		{
			this._Feats = new EntitySet<Feats>(new Action<Feats>(this.attach_Feats), new Action<Feats>(this.detach_Feats));
			this._Adresses = default(EntityRef<Adresses>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naissance", DbType="DateTime2 NOT NULL")]
		public System.DateTime Naissance
		{
			get
			{
				return this._Naissance;
			}
			set
			{
				if ((this._Naissance != value))
				{
					this.OnNaissanceChanging(value);
					this.SendPropertyChanging();
					this._Naissance = value;
					this.SendPropertyChanged("Naissance");
					this.OnNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(MAX)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inscription", DbType="Date NOT NULL")]
		public System.DateTime Inscription
		{
			get
			{
				return this._Inscription;
			}
			set
			{
				if ((this._Inscription != value))
				{
					this.OnInscriptionChanging(value);
					this.SendPropertyChanging();
					this._Inscription = value;
					this.SendPropertyChanged("Inscription");
					this.OnInscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mdp", DbType="NVarChar(MAX)")]
		public string Mdp
		{
			get
			{
				return this._Mdp;
			}
			set
			{
				if ((this._Mdp != value))
				{
					this.OnMdpChanging(value);
					this.SendPropertyChanging();
					this._Mdp = value;
					this.SendPropertyChanged("Mdp");
					this.OnMdpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexeId", DbType="Int")]
		public System.Nullable<int> SexeId
		{
			get
			{
				return this._SexeId;
			}
			set
			{
				if ((this._SexeId != value))
				{
					this.OnSexeIdChanging(value);
					this.SendPropertyChanging();
					this._SexeId = value;
					this.SendPropertyChanged("SexeId");
					this.OnSexeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdresseId", DbType="Int")]
		public System.Nullable<int> AdresseId
		{
			get
			{
				return this._AdresseId;
			}
			set
			{
				if ((this._AdresseId != value))
				{
					if (this._Adresses.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdresseIdChanging(value);
					this.SendPropertyChanging();
					this._AdresseId = value;
					this.SendPropertyChanged("AdresseId");
					this.OnAdresseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Membres_Feats", Storage="_Feats", ThisKey="Id", OtherKey="CreateurId")]
		public EntitySet<Feats> Feats
		{
			get
			{
				return this._Feats;
			}
			set
			{
				this._Feats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adresses_Membres", Storage="_Adresses", ThisKey="AdresseId", OtherKey="Id", IsForeignKey=true)]
		public Adresses Adresses
		{
			get
			{
				return this._Adresses.Entity;
			}
			set
			{
				Adresses previousValue = this._Adresses.Entity;
				if (((previousValue != value) 
							|| (this._Adresses.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adresses.Entity = null;
						previousValue.Membres.Remove(this);
					}
					this._Adresses.Entity = value;
					if ((value != null))
					{
						value.Membres.Add(this);
						this._AdresseId = value.Id;
					}
					else
					{
						this._AdresseId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Adresses");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Feats(Feats entity)
		{
			this.SendPropertyChanging();
			entity.Membres = this;
		}
		
		private void detach_Feats(Feats entity)
		{
			this.SendPropertyChanging();
			entity.Membres = null;
		}
	}
}
#pragma warning restore 1591
